Tracer_Study/Alumni/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.welcome, name='welcome'),
    path('home', views.base, name='home'),

   
]

Tracer_Study/Tracer_Study/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Alumni.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Tracer_Study/Alumni/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class GraduatedStudent(models.Model):
    names = models.CharField(max_length=200, blank=False)
    faculty = models.CharField(max_length=6, blank=False)
    course = models.CharField(max_length=200, blank=False)
    student_number = models.CharField(max_length=9, blank=False, primary_key=True)
    graduation_year = models.CharField(max_length=4, blank=False)

    def __str__(self):
        return self.names


class EmploymentAnalysis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    student_number = models.CharField(max_length=9, blank=False, primary_key=True)
    faculty = models.CharField(max_length=50, blank=True)
    course = models.CharField(max_length=200, blank=False)
    graduation_year = models.CharField(max_length=4, blank=False)
    employment_status = models.CharField(max_length=100, blank=False)
    company_name = models.CharField(max_length=100, blank=True)
    email = models.CharField(max_length=100, blank=True)
    contacts = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.student_number


class AlumniProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False, default=1)
    names = models.CharField(max_length=200)
    student_number = models.CharField(max_length=9, unique=True)
    faculty = models.CharField(max_length=6, )
    course = models.CharField(max_length=100)
    graduation_year = models.CharField(max_length=4)
    password = models.CharField(max_length=128)


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=False, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True,
                                        null=True)  # Define the profile picture field


class StudentsSurvey(models.Model):
    ARE_SATISFIED_CHOICES = [
        ('Satisfied', 'Satisfied'),
        ('I am not Satisfied', 'I am not Satisfied'),
        ('I am not sure', 'I am not sure'),
    ]

    COURSES_CHOICES = [
        ('DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA', 'DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA'),
        ('DEGREE IN BUSINESS INFORMATION TECHNOLOGY', 'DEGREE IN BUSINESS INFORMATION TECHNOLOGY'),
        ('DEGREE IN INFORMATION TECHNOLOGY', 'DEGREE IN INFORMATION TECHNOLOGY'),
        ('DEGREE IN FASHION & APPAREL DESIGN', 'DEGREE IN FASHION & APPAREL DESIGN'),
        ('DEGREE IN CREATIVE ADVERTISING', 'DEGREE IN CREATIVE ADVERTISING'),
        ('DEGREE IN GRAPHIC DESIGN', 'DEGREE IN GRAPHIC DESIGN'),
        ('DEGREE IN HOTEL MANAGEMENT', 'DEGREE IN HOTEL MANAGEMENT'),
        ('DEGREE IN TOURISM MANAGEMENT', 'DEGREE IN TOURISM MANAGEMENT'),
        ('DEGREE IN INTERNATIONAL TOURISM', 'DEGREE IN INTERNATIONAL TOURISM'),

    ]

    REASON = [
        ('Career Advancement', 'Career Advancement'),
        ('Personal Interest', 'Personal Interest'),
        ('To acquire new skills', 'To acquire new skills'),
        ('Others', 'Others'),
    ]

    RATINGS = [
        ('Very Poor', 'Very Poor'),
        ('Poor', 'Poor'),
        ('Average', 'Average'),
        ('Good', 'Good'),
        ('Excellent', 'Excellent'),
    ]

    DEGREE_LEVEL = [
        ('Bachelor1`s Degree', 'Bachelor1`s Degree'),
        ('Bachelor of Arts', 'Bachelor of Arts'),
        ('Associate Degree', 'Associate Degree'),
        ('TVET', 'TVET'),
    ]

    GENDER = [
        ('Male', 'Male',),
        ('Female', 'Female')
    ]

    FACULTY = [
        ('FDI', 'FDI'),
        ('FICT', 'FICT'),
        ('FCTH', 'FCTH'),
        ('FCMB', 'FCMB'),
    ]

    PROGRAM_SATISFACTION = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    FACULTY_KNOWLEDGE = [
        ('Excellent', 'Excellent'),
        ('Very Good', 'Very Good'),
        ('Good', 'Good'),
        ('Fair', 'Fair'),
        ('Poor', 'Poor')
    ]

    ACADEMIC_ADVISORS = [
        ('Very helpful', 'Very helpful'),
        ('Somewhat helpful', 'Somewhat helpful'),
        ('Neutral', 'Neutral'),
        ('Somewhat unhelpful', 'Somewhat unhelpful'),
        ('Very unhelpful', 'Very unhelpful')
    ]

    CURRICULUM = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    CAMPUS_FACILITIES = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    PROGRAM_SUPPORT = [
        ('Very well', 'Very well'),
        ('Somewhat well', 'Somewhat well'),
        ('Neutral', 'Neutral'),
        ('Somewhat poorly', 'Somewhat poorly'),
        ('Very poorly', 'Very poorly')
    ]

    faculty = models.CharField(max_length=6, choices=FACULTY)
    degree_level = models.CharField(max_length=100, choices=DEGREE_LEVEL)
    course = models.CharField(max_length=100, choices=COURSES_CHOICES)
    gender = models.CharField(max_length=10, choices=GENDER)
    reason = models.CharField(max_length=100, choices=REASON)
    program_satisfaction = models.CharField(max_length=100, choices=PROGRAM_SATISFACTION)
    faculty_knowledge = models.CharField(max_length=100, choices=FACULTY_KNOWLEDGE)
    curriculum_satisfaction = models.CharField(max_length=100, choices=CURRICULUM)
    academic_advisors = models.CharField(max_length=100, choices=ACADEMIC_ADVISORS)
    campus_facilities_satisfaction = models.CharField(max_length=100, choices=CAMPUS_FACILITIES)
    extracurricular = models.CharField(max_length=100, choices=CAMPUS_FACILITIES)
    program_support = models.CharField(max_length=100, choices=PROGRAM_SUPPORT)
    career_goals = models.CharField(max_length=100, choices=PROGRAM_SUPPORT)
    career_services = models.CharField(max_length=100, choices=COURSES_CHOICES)
    comments = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.faculty} - {self.course} - {self.gender}"


class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255)
    company_description = models.TextField()
    company_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    website = models.URLField(blank=True, null=True)
    address = models.TextField()
    is_approved = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to='employer_profile_pictures/', blank=True, null=True)
    cover_picture = models.ImageField(upload_to='employer_cover_pictures/', blank=True, null=True)

    def __str__(self):
        return self.company_name


class JobPosting(models.Model):
    WORKPLACE_TYPE_CHOICES = [
        ('On-site', 'On-site'),
        ('Remote', 'Remote'),
        ('Hybrid', 'Hybrid'),
    ]

    JOB_TYPE_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
        ('Internship', 'Internship'),
    ]

    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='job_postings')
    job_title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    workplace_type = models.CharField(max_length=50, choices=WORKPLACE_TYPE_CHOICES)
    job_location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)
    description = models.TextField()
    skills = models.TextField()
    deadline = models.DateField(null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job_title


class InternshipPosting(models.Model):
    WORKPLACE_TYPE_CHOICES = [
        ('On-site', 'On-site'),
        ('Remote', 'Remote'),
        ('Hybrid', 'Hybrid'),
    ]

    JOB_TYPE_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
        ('Internship', 'Internship'),
    ]

    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, null=True)
    job_title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    workplace_type = models.CharField(max_length=50, choices=WORKPLACE_TYPE_CHOICES)
    job_location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)
    description = models.TextField()
    skills = models.TextField()
    deadline = models.DateField(null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job_title


class ProfessionalDetails(models.Model):
    EMPLOYMENT_STATUS_CHOICES = [
        ('unemployed', 'Unemployed'),
        ('employed', 'Employed'),
        ('self_employed', 'Self Employed'),
        ('studying', 'Studying'),
        ('self_employed_employed', 'Self Employed and Employed'),
        ('employed_studying', 'Employed and Studying'),
        ('self_employed_studying', 'Self Employed and Studying'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    employment_status = models.CharField(max_length=100, choices=EMPLOYMENT_STATUS_CHOICES)
    skills = models.CharField(max_length=100, blank=False, null=False)
    company_name = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

Tracer_Study/Alumni/views.py
from django.shortcuts import render

from .models import JobPosting
from .models import InternshipPosting


def welcome(request):
    return render(request, "alumni/basetemplates/intro.html", {})


def base(request):
    job_postings = JobPosting.objects.all().order_by('-created_at')[:3]
    internship = InternshipPosting.objects.all().order_by('-created_at')[:3]

    context = {
        'job_postings': job_postings,
        'internship_posting': internship
    }
    return render(request, "alumni/basetemplates/base.html", context)

Tracer_Study/Alumni/templates/alumni/authent/account_info.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="x-icon" href="{% static 'images/download.png'%}">
    <link rel="stylesheet" href="{% static 'stylesheet/signup.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Sign Up </title>
  </head>
  <body>
    <div class="container-fluid justify-content-center" style="margin-top: 100px;">
      <form class="row g-3 mx-auto" action="" method="post">
        {% csrf_token %}
        <div class="text-center" >
          <img src="{% static 'images/download.png'%}" class="img-thumbnail" alt="No image found">
        </div>

                <br>
        <br>
                <br>
        <br>
        <h3 class="text-center" style="margin-top: 50px;" >Register with LUCT Career Services</h3>

        <br>
        <br>
        <h5 class="text-center">Profile Information</h5>
        <br>
        <br>

        <div class="mb-3">
          <label  class="form-label">Email address</label>
          <input type="email"   name="email" class="form-control" id="email" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        
        <div class="">
          <label class="form-label">Username</label>
          <div class="input-group has-validation">
            <span class="input-group-text" id="inputGroupPrepend4">@</span>
            <input type="text" name="username" class="form-control" id="username" required>
          </div>
        </div>

        <div class="mb-3">
          <label  class="form-label">Password</label>
          <input type="password" name="password" class="form-control" id="password">
        </div>

        <div class="mb-3">
          <label class="form-label" >Confirm Password</label>
          <input type="password" name="confirm_password" class="form-control" id="confirm_password">
        </div>


        {% if form.errors %}
          <p class="error-message" style="color: red;">There were errors in your submission. Please correct them and try again.</p>
        {% endif %}


        <div class="col-12">
          <button class="btn btn-dark btn-lg" type="submit">REGISTER</button>
        </div>

        <br>
        <div>
             <label class="label">Already had an account?</label>
             <a href="{% url 'signIn' %}">Sign In</a>
        </div>

        <br>
        <br>
        <label class="text-center">These pages are part of </label>
        <div class=" fluid-container justify-content: center">
          <a href="">Cookies Info</a>
          <label>            |               </label>
          <a href="">Privacy notice</a>
          <label>            |               </label>
          <a href="">LUCT Career Services Privacy policy</a>
          <label>            |               </label>
          <a href="">Terms and Conditions</a>
        </div>

    </form>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

Tracer_Study/Alumni/templates/alumni/authent/alumni_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumni Success</title>
</head>
<body>
    <h1>Employment status added successfully!</h1>
    <!-- You can add additional content or redirect users after success -->

    <a href="{% url 'info_preview' %}" class="btn btn-primary">Preview Information</a>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/authent/conf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumni Confirmation</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>

    <h1>Alumni Confirmation</h1>
    <p>Name: {{ graduating_student.name }}</p>
    <p>Name: {{ graduating_student.name }}</p>
    <p>Name: {{ graduating_student.name }}</p>
    <p>Program: {{ graduating_student.program }}</p>
    <p>Graduation Year: {{ graduating_student.year }}</p>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/authent/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumni Registration</title>



</head>
<body style="background-color: #455A64; color: #fff;">
    <div style="justify-content: center; padding: center;">
        <h1>Alumni Registration</h1>
        <p>
            You must enter your student number to check yourself if you exist in University Career Services database. Only graduated students can be able to register in Career Connect Platform.
        </p>


        <br>

        <p style="color: #E0E0E0;">
            Please enter "None" if employment status is Unemployed
        </p>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-secondary btn-lg">Submit Employment Status</button>

            {% if error_message %}
            <p>{{ error_message }}</p>
            {% endif %}
        </form>
    </div>
    <script>
        $(document).ready(function() {
            $('#id_employment_status').change(function() {
                if ($(this).val() === 'Unemployed') {
                    $('#id_company_name').val('No Company');
                    $('#id_company_name').prop('readonly', true); // Optional: Make the field readonly
                } else {
                    $('#id_company_name').val(''); // Reset the field if not 'Unemployed'
                    $('#id_company_name').prop('readonly', false); // Optional: Make the field editable
                }
            });
        });
</script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</body>
</html>

Tracer_Study/Alumni/templates/alumni/authent/signIn.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="x-icon" href="{% static 'images/download.png'%}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'stylesheet/login.css' %}">
    <title>Log In</title>
  </head>
  <body>
    <div class="container-fluid justify-content-center">
      <form class="mx-auto" method="post" >

        {% csrf_token %}

            <div class="text-center" >
              <img src="{% static 'images/download.png'%}" class="img-thumbnail" alt="No image found">
            </div>


            <br>
            <br>
            <h2 class="text-center fw-bold" style="font-weight: bold;">Log In to LUCT Career Services</h2>
            <br>
            <h4>Logging-in adds a cookie to your computer</h4>
            <br>

            <label style="font-weight: bold; font-size: 30px;">Log In</label>
            <br>
            <br>
            <div class="mb-3">
            <br>
            <br>
            <div class="mb-3">
              <label class="form-label" style="font-weight: bold" >Username</label>
              <input type="text" class="form-control" name="username">
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label" style="font-weight: bold" >Password</label>

          <input type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div>
             <a href="">Forgot your password</a>
        </div>
        <br>

        <button type="submit" class="btn btn-dark btn-lg">Log In</button>
        <br>
        <br>
        <div>
             <label class="label">Not have an account?</label>
             <a href="{% url 'signUp' %}">Sign Up</a>
        </div>

        <br>
        <label class="text-center">These pages are part of </label>
        <div class=" fluid-container justify-content: center">
          <a href="">Cookies Info</a>
          <label>            |               </label>
          <a href="">Privacy notice</a>
          <label>            |               </label>
          <a href="">LUCT Career Services Privacy policy</a>
          <label>            |               </label>
          <a href="">Terms and Conditions</a>
        </div>
            </div>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

Tracer_Study/Alumni/templates/alumni/authent/signOut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>