Tracer_Study/Alumni/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.welcome, name='welcome'),
    path('home', views.base, name='home'),

   
]

Tracer_Study/Tracer_Study/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Alumni.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Tracer_Study/Alumni/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class GraduatedStudent(models.Model):
    names = models.CharField(max_length=200, blank=False)
    faculty = models.CharField(max_length=6, blank=False)
    course = models.CharField(max_length=200, blank=False)
    student_number = models.CharField(max_length=9, blank=False, primary_key=True)
    graduation_year = models.CharField(max_length=4, blank=False)

    def __str__(self):
        return self.names


class EmploymentAnalysis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    student_number = models.CharField(max_length=9, blank=False, primary_key=True)
    faculty = models.CharField(max_length=50, blank=True)
    course = models.CharField(max_length=200, blank=False)
    graduation_year = models.CharField(max_length=4, blank=False)
    employment_status = models.CharField(max_length=100, blank=False)
    company_name = models.CharField(max_length=100, blank=True)
    email = models.CharField(max_length=100, blank=True)
    contacts = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.student_number


class AlumniProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False, default=1)
    names = models.CharField(max_length=200)
    student_number = models.CharField(max_length=9, unique=True)
    faculty = models.CharField(max_length=6, )
    course = models.CharField(max_length=100)
    graduation_year = models.CharField(max_length=4)
    password = models.CharField(max_length=128)


class UserProfile(models.Model):
    user = models.OneToOneField(User, null=False, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True,
                                        null=True)  # Define the profile picture field


class StudentsSurvey(models.Model):
    ARE_SATISFIED_CHOICES = [
        ('Satisfied', 'Satisfied'),
        ('I am not Satisfied', 'I am not Satisfied'),
        ('I am not sure', 'I am not sure'),
    ]

    COURSES_CHOICES = [
        ('DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA', 'DEGREE IN SOFTWARE ENGINEERING & MULTIMEDIA'),
        ('DEGREE IN BUSINESS INFORMATION TECHNOLOGY', 'DEGREE IN BUSINESS INFORMATION TECHNOLOGY'),
        ('DEGREE IN INFORMATION TECHNOLOGY', 'DEGREE IN INFORMATION TECHNOLOGY'),
        ('DEGREE IN FASHION & APPAREL DESIGN', 'DEGREE IN FASHION & APPAREL DESIGN'),
        ('DEGREE IN CREATIVE ADVERTISING', 'DEGREE IN CREATIVE ADVERTISING'),
        ('DEGREE IN GRAPHIC DESIGN', 'DEGREE IN GRAPHIC DESIGN'),
        ('DEGREE IN HOTEL MANAGEMENT', 'DEGREE IN HOTEL MANAGEMENT'),
        ('DEGREE IN TOURISM MANAGEMENT', 'DEGREE IN TOURISM MANAGEMENT'),
        ('DEGREE IN INTERNATIONAL TOURISM', 'DEGREE IN INTERNATIONAL TOURISM'),

    ]

    REASON = [
        ('Career Advancement', 'Career Advancement'),
        ('Personal Interest', 'Personal Interest'),
        ('To acquire new skills', 'To acquire new skills'),
        ('Others', 'Others'),
    ]

    RATINGS = [
        ('Very Poor', 'Very Poor'),
        ('Poor', 'Poor'),
        ('Average', 'Average'),
        ('Good', 'Good'),
        ('Excellent', 'Excellent'),
    ]

    DEGREE_LEVEL = [
        ('Bachelor1`s Degree', 'Bachelor1`s Degree'),
        ('Bachelor of Arts', 'Bachelor of Arts'),
        ('Associate Degree', 'Associate Degree'),
        ('TVET', 'TVET'),
    ]

    GENDER = [
        ('Male', 'Male',),
        ('Female', 'Female')
    ]

    FACULTY = [
        ('FDI', 'FDI'),
        ('FICT', 'FICT'),
        ('FCTH', 'FCTH'),
        ('FCMB', 'FCMB'),
    ]

    PROGRAM_SATISFACTION = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    FACULTY_KNOWLEDGE = [
        ('Excellent', 'Excellent'),
        ('Very Good', 'Very Good'),
        ('Good', 'Good'),
        ('Fair', 'Fair'),
        ('Poor', 'Poor')
    ]

    ACADEMIC_ADVISORS = [
        ('Very helpful', 'Very helpful'),
        ('Somewhat helpful', 'Somewhat helpful'),
        ('Neutral', 'Neutral'),
        ('Somewhat unhelpful', 'Somewhat unhelpful'),
        ('Very unhelpful', 'Very unhelpful')
    ]

    CURRICULUM = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    CAMPUS_FACILITIES = [
        ('Very satisfied', 'Very satisfied'),
        ('Somewhat satisfied', 'Somewhat satisfied'),
        ('Neutral', 'Neutral'),
        ('Somewhat dissatisfied', 'Somewhat dissatisfied'),
        ('Very dissatisfied', 'Very dissatisfied')
    ]

    PROGRAM_SUPPORT = [
        ('Very well', 'Very well'),
        ('Somewhat well', 'Somewhat well'),
        ('Neutral', 'Neutral'),
        ('Somewhat poorly', 'Somewhat poorly'),
        ('Very poorly', 'Very poorly')
    ]

    faculty = models.CharField(max_length=6, choices=FACULTY)
    degree_level = models.CharField(max_length=100, choices=DEGREE_LEVEL)
    course = models.CharField(max_length=100, choices=COURSES_CHOICES)
    gender = models.CharField(max_length=10, choices=GENDER)
    reason = models.CharField(max_length=100, choices=REASON)
    program_satisfaction = models.CharField(max_length=100, choices=PROGRAM_SATISFACTION)
    faculty_knowledge = models.CharField(max_length=100, choices=FACULTY_KNOWLEDGE)
    curriculum_satisfaction = models.CharField(max_length=100, choices=CURRICULUM)
    academic_advisors = models.CharField(max_length=100, choices=ACADEMIC_ADVISORS)
    campus_facilities_satisfaction = models.CharField(max_length=100, choices=CAMPUS_FACILITIES)
    extracurricular = models.CharField(max_length=100, choices=CAMPUS_FACILITIES)
    program_support = models.CharField(max_length=100, choices=PROGRAM_SUPPORT)
    career_goals = models.CharField(max_length=100, choices=PROGRAM_SUPPORT)
    career_services = models.CharField(max_length=100, choices=COURSES_CHOICES)
    comments = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.faculty} - {self.course} - {self.gender}"


class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=255)
    company_description = models.TextField()
    company_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    website = models.URLField(blank=True, null=True)
    address = models.TextField()
    is_approved = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to='employer_profile_pictures/', blank=True, null=True)
    cover_picture = models.ImageField(upload_to='employer_cover_pictures/', blank=True, null=True)

    def __str__(self):
        return self.company_name


class JobPosting(models.Model):
    WORKPLACE_TYPE_CHOICES = [
        ('On-site', 'On-site'),
        ('Remote', 'Remote'),
        ('Hybrid', 'Hybrid'),
    ]

    JOB_TYPE_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
        ('Internship', 'Internship'),
    ]

    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='job_postings')
    job_title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    workplace_type = models.CharField(max_length=50, choices=WORKPLACE_TYPE_CHOICES)
    job_location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)
    description = models.TextField()
    skills = models.TextField()
    deadline = models.DateField(null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job_title


class InternshipPosting(models.Model):
    WORKPLACE_TYPE_CHOICES = [
        ('On-site', 'On-site'),
        ('Remote', 'Remote'),
        ('Hybrid', 'Hybrid'),
    ]

    JOB_TYPE_CHOICES = [
        ('Full-time', 'Full-time'),
        ('Part-time', 'Part-time'),
        ('Contract', 'Contract'),
        ('Temporary', 'Temporary'),
        ('Internship', 'Internship'),
    ]

    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, null=True)
    job_title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    workplace_type = models.CharField(max_length=50, choices=WORKPLACE_TYPE_CHOICES)
    job_location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=50, choices=JOB_TYPE_CHOICES)
    description = models.TextField()
    skills = models.TextField()
    deadline = models.DateField(null=True, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job_title


class ProfessionalDetails(models.Model):
    EMPLOYMENT_STATUS_CHOICES = [
        ('unemployed', 'Unemployed'),
        ('employed', 'Employed'),
        ('self_employed', 'Self Employed'),
        ('studying', 'Studying'),
        ('self_employed_employed', 'Self Employed and Employed'),
        ('employed_studying', 'Employed and Studying'),
        ('self_employed_studying', 'Self Employed and Studying'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    employment_status = models.CharField(max_length=100, choices=EMPLOYMENT_STATUS_CHOICES)
    skills = models.CharField(max_length=100, blank=False, null=False)
    company_name = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

Tracer_Study/Alumni/views.py
from django.shortcuts import render

from .models import JobPosting
from .models import InternshipPosting


def welcome(request):
    return render(request, "alumni/basetemplates/intro.html", {})


def base(request):
    job_postings = JobPosting.objects.all().order_by('-created_at')[:3]
    internship = InternshipPosting.objects.all().order_by('-created_at')[:3]

    context = {
        'job_postings': job_postings,
        'internship_posting': internship
    }
    return render(request, "alumni/basetemplates/base.html", context)

Tracer_Study/Alumni/templates/alumni/alum_reg/alumni_profiles.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="x-icon" href="{% static 'images/download.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employers List</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'stylesheet/navbar.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        .card {
            background-color: #000;
            color: white;
            margin-bottom: 20px;
            width: 350px; /* Set a fixed width for the cards */
            border-radius: 10px;
            overflow: hidden; /* Ensure the content does not overflow the card's boundaries */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-bottom: 50px;
        }
        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }
        .card img.cover-picture {
            width: 100%;
            height: 150px;
            object-fit: cover; /* Ensure the image covers the entire area */
        }
        .card img.profile-picture {
            width: 150px;
            height: 150px;
            object-fit: cover;
            border-radius: 50%; /* Make the profile picture circular */
            position: absolute;
            top: 60px;
            left: 50%;
            transform: translateX(-50%);
            border: 5px solid #000; /* Optional: Add a border around the profile picture */
        }
        .card-container {
            display: flex;
            flex-wrap: wrap;
            gap: 120px;
            justify-content: center; /* Center align the cards */
        }
        .card-body {
            padding-top: 60px; /* Adjust to make space for the profile picture */
            text-align: center;
        }
        .view-profile-link {
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            padding: 8px 16px;
            border-radius: 4px;
            transition: all 0.3s ease;
            top: 20px;
        }
        .view-profile-link:hover {
            background-color: #0056b3;
            color: #fff;
        }
    </style>
</head>
<body>

    {% include 'alumni/alum_reg/nav.html' %}

    <div class="container mt-5">
        <h1 class="mb-4 text-center fw-bold" style="margin-bottom: 50px;">List of Alumni Profiles</h1>
        <div class="card-container">
            {% for alumni in alumni_profiles %}
                <div class="card" >
                    {% if alumni.cover_picture %}
                        <img src="{{ alumni.cover_picture.url }}" class="cover-picture" alt="Cover Picture">
                    {% endif %}
                    {% if alumni.profile_picture %}
                        <img src="{{ alumni.profile_picture.url }}" class="profile-picture" alt="Profile Picture">
                    {% endif %}
                    <div class="card-body" style="margin-bottom: 50px;">
                        <h5 class="card-title fw-bold" style="margin-top: 30px;">{{ alumni.user.first_name }} {{ alumni.user.last_name }}</h5>
                        <p class="card-text" style="margin-bottom: 20px; padding: 20px;">
                            <strong>Employment Status:</strong> {{ alumni.employment_status }}<br>
                            <strong>Company:</strong> {{ alumni.company_name }}
                        </p>
                        <a href="{% url 'alumni_profile' alumni.user.username %}" class="view-profile-link btn btn-secondary" style="margin-top: 25px;">View Profile</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/

    +-npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/alum_reg/apply_internship.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Apply for Internship</title>
    <link rel="stylesheet" href="{% static 'stylesheet/navbar.css' %}">
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body style="background-color: black;">
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                <strong>{{ message }}</strong><br>
            {% endfor %}
        </div>
    {% endif %}
    <div class="container mt-5" style=" width: 55%; background-color: #CFD8DC; padding: 80px 100px; margin-left: 350px; margin-right: 200px;">
        <h2 class="mb-4 text-center fw-bold fs-2">Apply for Internship</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_full_name" class="form-label">Full Name</label>
                <input type="text" class="form-control" id="id_full_name" name="full_name" required>
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email Address</label>
                <input type="email" class="form-control" id="id_email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="id_phone_number" class="form-label">Phone Number</label>
                <input type="text" class="form-control" id="id_phone_number" name="phone_number" required>
            </div>
            <div class="mb-3">
                <label for="id_gpa" class="form-label">GPA</label>
                <input type="number" step="0.01" class="form-control" id="id_gpa" name="gpa" required>
            </div>
            <div class="mb-3">
                <label for="id_previous_internships" class="form-label">Previous Internships</label>
                <textarea class="form-control" id="id_previous_internships" name="previous_internships" rows="3" required></textarea>
            </div>
            <div class="mb-3">
                <label for="id_skills" class="form-label">Skills and Qualifications</label>
                <textarea class="form-control" id="id_skills" name="skills" rows="3" required></textarea>
            </div>
            <div class="mb-3">
                <label for="id_cover_letter" class="form-label">Cover Letter</label>
                <textarea class="form-control" id="id_cover_letter" name="cover_letter" rows="5" required></textarea>
            </div>
            <div class="mb-3">
                <label for="id_resume" class="form-label">Resume/CV Upload</label>
                <input type="file" class="form-control" id="id_resume" name="resume" accept=".pdf,.doc,.docx" required>
            </div>
            <button type="submit" class="btn bg-black" style=" margin-left: 250px; color: #fff;">Submit Application</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/alum_reg/apply_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application Success</title>
    <!-- Include Bootstrap CSS or your preferred styling -->
</head>
<body>
    <div class="container mt-5">
        <h2 class="mb-4 text-center fw-bold fs-2">Application Submitted Successfully</h2>
        <p class="text-center">Thank you for applying for the internship. We will review your application and get back to you soon.</p>
        <p class="text-center"><a href="{% url 'home' %}" class="btn btn-primary">Back to Home</a></p>
    </div>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/alum_reg/available_internship.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="x-icon" href="{% static 'images/download.png'%}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Available Internships</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'stylesheet/navbar.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .card {
            background-color: #000;
            color: white;
            margin-bottom: 20px;
            width: calc(35% - 20px);
            max-width: 350px; /* Limit the max width of the card */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        .card:hover {
            transform: scale(1.05);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
        }
        .card h5, .card p, .card a {
            color: white;
        }
        .card a {
            text-decoration: underline;
        }
        .card-container {
            display: flex;
            flex-wrap: wrap;
            gap: 180px;
            justify-content: flex-start;
        }
    </style>
</head>
<body style="background-color: #CFD8DC;">
    {% include 'alumni/alum_reg/nav.html' %}
    <div class="container mt-5" style="margin-top: 20px; margin-bottom: 20px; margin-left: 150px; margin-right: 80px;">
        <h2 class="mb-4 text-center fw-bold fs-2" style="margin-bottom: 50px;">Available Internships</h2>

        {% load humanize %}

        <div class="card-container" style="margin-top: 60px;">
            {% for internship in internship_posting %}
                <div class="card" style="margin-left: -50px;">
                    <div class="card-body">
                        <label class="card-title" style="margin-left: 80px; font-weight: bold; font-size: 15px">{{ internship.job_title }}</label>
                        <p class="card-text">
                            <strong>Company:</strong> {{ internship.company }}<br>
                            <strong>Internship:</strong> {{ internship.description | safe }}<br>
                            <strong>Deadline:</strong> {{ internship.deadline }}<br>
                            <strong>Posted:</strong> <label style="color: red; font-weight: italic;">{{ internship.created_at|naturaltime }}</label>
                        </p>
                        <div class="container">
                            <a href="{% url 'internship_detail' internship.id %}" class="card-link" style="margin-left: 80px;">View Internship</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!-- Include Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

Tracer_Study/Alumni/templates/alumni/alum_reg/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User Account</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-Gnj8H5Y8/XQ0o9xx78G8q6vb18TrjsKb4I9h/sU3Aa0uVIGUwFqHeLOhHUURayDp" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'stylesheet/navbar.css' %}">

    <style>

        body {
            background-color: #f8f9fa;
            padding: 20px;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        .form-control {
            width: 100%;
            padding: 10px;
            border: 1px solid #ced4da;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .btn {
            width: 40%;
            padding: 10px;
            border: none;
            background-color: black;
            color: white;
            font-size: 16px;
            cursor: pointer;
            border-radius: 4px;
            margin-left: 170px;
        }

        .btn:hover {
            background-color: #0056b3;
        }


        .form-control.password-field {
            width: 100%;
            height: 50px;
            padding: 10px;
        }
    </style>
</head>
<body style="background-color: #000;">
    <div class="container mt-5" style="background-color: #CFD8DC; margin-top: 100px;">
        <img src="{% static 'images/download.png'%}" style="margin-left:300; padding:0px 200px" alt="Logo" width="200" height="90" class="d-inline-block align-text-middle">
        <h2>Create User Account</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            <div class="form-group mb-3">
                {{ form.first_name.label_tag }}
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>
            <div class="form-group mb-3">
                {{ form.last_name.label_tag }}
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>
            <div class="form-group mb-3">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                {{ form.password1.errors }}
            </div>
            <div class="form-group mb-3" style="width: 100%">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
                {{ form.password2.errors }}
            </div>
            <div class="form-group mb-3">
                {{ form.profile_picture.label_tag }}
                {{ form.profile_picture }}
                {{ form.profile_picture.errors }}
            </div>
            <div class="form-group mb-3">
                {{ form.cover_picture.label_tag }}
                {{ form.cover_picture }}
                {{ form.cover_picture.errors }}
            </div>
            <button type="submit" class="btn btn-primary">Create Account</button><br><br>
            <label>Already have an account? <a href="{% url 'alumni_login' %}">Login</a></label>
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>